### ISSUE TITLE
Level 1 Designing

### ISSUE THREAD

**Issue by WillTarte** [WillTarte/EMU#10]
As a level designer, I can create multiple levels using the available assets & prefabs.
- [x] I can create ground tiles to the level.
- [x] I can add platforming elements to the level.
- [ ] I can add the player character to the level, and it should be able to traverse it. (See #4 )
- [ ] I can add interactable objects to the level. (See #13 )
- [ ] I can add enemies to the level. (See #12 )
- [ ] I can add trigger zones to the level. (See #11 )
