### ISSUE TITLE
[STRETCH] Save Game Functionality

### ISSUE THREAD

**Issue by WillTarte** [WillTarte/EMU#2]
As a player, I can save the game.
- [ ] On the pause screen, There is a "Save Game" button. (See #3 ) 
- [ ] Pressing the "Save Game" button saves the game. (See #3 )
  - [ ] Saves current level
  - [ ] Saves current stats
  - [ ] Saves current loadout
- [ ] I can see the save from the Main Menu's "Load Game" screen (See #1 )
- [ ] I can load a save from the Main Menu. (See #1 )

**Comment by ClaudiaLapalme** [comment]
Closing the stretch as we are reducing the scope of the project (we can always re-open it later if need be)
