### ISSUE TITLE
Player Weapons System

### ISSUE THREAD

**Issue by WillTarte** [WillTarte/EMU#5]
As a developer, I can easily create new weapons that are usable by the player character.
- [ ] Weapon prefab
  - [ ] Has a sprite
  - [ ] Has a Magazine capacity
  - [ ] Has a total amount of ammunition
  - [ ] Has a durability?
  - [ ] Has a projectile when the player shoots
- [ ] Is interactable (player pickup) (See #13 )
- [ ] Can reload if enough ammunition, and magazine is not full
- [ ] Has a state that dictates it's appearance
  - [ ] In Player inventory (visible in player's UI) (See #6 )
  - [ ] Is currently equipped (visible in player's UI and model) (See #6 )
  - [ ] Is on the ground (interactable)
  - [ ] Is hidden in some kind of container (not visible unless container broken/opened)

#8 Is the task for art. Keep this task up to date with types of weapons implemented
---
List of weapons:
https://docs.google.com/document/d/16qc2BVcy2TmGjTB14U8xD21yn4BewymAo-PWEDZw0bE/edit
